### ISSUE TITLE
Add gutters to the homepage

### ISSUE THREAD

**Issue by bcipolli** [opensandiego/website-wordpress#12]
Homepage content is way too wide; add left and right margins (gutters) so that it gives a clean single-column feel.

**Comment by bcipolli** [comment]
I.e. something like this:
![image](https://cloud.githubusercontent.com/assets/4072455/11914960/225c0422-a646-11e5-81f0-ee22e3af6ea8.png)

instead of:
![image](https://cloud.githubusercontent.com/assets/4072455/11914962/30713b0e-a646-11e5-9792-4203c3d02e90.png)

**Comment by jerryhall** [comment]
Still trying to resolve 3-feature boxes not displaying correctly. In any case site is 1040px now.
