### ISSUE TITLE
Bad Link to GH on Homepage

### ISSUE THREAD

**Issue by bspaulding** [opensandiego/website-wordpress#19]
Hey all,

Just noticed there's a bad link on the homepage:

"See our full list of projects and repositories on [GitHub]" links to https://github.com/codeforsandiego.

Seems like you changed your name at some point? :)

I'm happy to PR a fix, but it doesn't look like that site's source is on GH? Is it up anywhere PR-able?

**Comment by merelyanode** [comment]
Thanks for pointing that out @bspaulding.  Our website is a bit of a pain point right now.  I'd like to see it as Jekyll site so we can manage the source on Github.  For now though, the best we can do is give folks access to the WP interface to make corrections.  For now, @cgiovando can you correct the mistake Bradley has identified?  @jerryhall

**Comment by cgiovando** [comment]
I don't have access to WP..

@jerryhall - can you help?

**Comment by jerryhall** [comment]
Fixed. 
I also just emailed you the login/pass to WP as well Cristiano but, don't mind making the changes if people post them here.
